/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapp1;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Dennis
 */
public class NewJPanel extends javax.swing.JPanel {

   JClock jClock = new JClock();
   private static final String[] decimales = {
    "",
    " diez",
    " veinte",
    " treinta",
    " cuarenta",
    " cincuenta",
    " sesenta",
    " setenta",
    " ochenta",
    " noventa"
  };
   
   private static final String[] numeros = {
    "",
    " uno",
    " dos",
    " tres",
    " cuatro",
    " cinco",
    " seis",
    " siete",
    " ocho",
    " nueve",
    " diez",
    " once",
    " doce",
    " tres",
    " catorce",
    " quince",
    " diciseis",
    " diecisiete",
    " dieciocho",
    " diecinueve"
  };
    public class JClock extends javax.swing.JPanel implements ActionListener{
    //Declaramos el timer con 1000 milisegundos, y el oyente la misma clase 
        Timer timer = new Timer(1000,this);    

        
   //En el constructor iniciamos el timer 
        public JClock() {
            initComponents();
            timer.start();
            jTextField2.addKeyListener(new KeyAdapterNumbersOnly());
            jTextField2.setText("");
        }    
    
        @Override
         //implementamos el método y asignamos la hora actual a la etiqueta lblClock
         public void actionPerformed(ActionEvent e) {
             SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss");         
             jLabel1.setText(sdf.format(new java.util.Date()));
         }    
   
    }
 
     class KeyAdapterNumbersOnly extends KeyAdapter {

            /**
             * Regular expression which defines the allowed characters.
             */
            private String allowedRegex = "[^0-9]";

            /**
             * Key released on field.
             */
            public void keyReleased(KeyEvent e) {
                String curText = ((JTextComponent) e.getSource()).getText();
                curText = curText.replaceAll(allowedRegex, "");

                ((JTextComponent) e.getSource()).setText(curText);

                if(curText  != "")
                {
                   jLabel2.setText(""); 
                   jLabel2.setText(showNumberName(Integer.parseInt(curText))); 
                }
            }
            
            private String showNumberName(int number) {
                String largo;

                if (number % 100 < 20){
                  largo = numeros[number % 100];
                }
                else {
                  largo = numeros[number % 10];
                  number /= 10;

                  largo = decimales[number % 10] + largo;
                  number /= 10;
                }
                if (number == 0) return largo;
                return numeros[number] + " cientos" + largo;
              }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("jLabel1");
        add(jLabel1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Boton 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, java.awt.BorderLayout.PAGE_END);

        jLabel2.setText("jLabel2");
        add(jLabel2, java.awt.BorderLayout.LINE_END);

        jTextField2.setText("jTextField2");
        add(jTextField2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel1.setText("Hola");
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}